### ISSUE TITLE
can not compile on Linux

### ISSUE THREAD

**Issue by tissatussa** [Nonlinear2/Bread-Engine#1]
i get errors when compiling on Linux .. i guess this is a minor fault in your code, can you fix it ?

at first i found 1 file is named with a capital letter : `src/Bread_engine_core.cpp`.
this way Linux can't find that file (on Windows the capital letter doesn't matter, on Linux it does), so i changed the file name to `bread_engine_core.cpp` 

then, here's what happened :

```
$ cmake . -DCMAKE_C_COMPILER=clang-17 -DCMAKE_CXX_COMPILER=clang++-17
-- The C compiler identification is Clang 17.0.6
-- The CXX compiler identification is Clang 17.0.6
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang-17 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++-17 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (0.9s)
-- Generating done (0.0s)
-- Build files have been written to: /home/roelof/Compiled/Bread-Engine-0.0.5
```

as you see, i added command line arguments to set clang v17, because my default clang version is 11.4.0

but, regardless the compiler version, this error occurs :

```
$ make
[  2%] Building CXX object CMakeFiles/release.dir/src/search_board.cpp.o
[  4%] Building CXX object CMakeFiles/release.dir/src/nnue/nnue.cpp.o
/home/roelof/Compiled/Bread-Engine-0.0.5/src/nnue/nnue.cpp:45:22: error: use of undeclared identifier 'nn_data'
   45 |         weights[i] = nn_data::weights[name][i];
      |                      ^
/home/roelof/Compiled/Bread-Engine-0.0.5/src/nnue/nnue.cpp:48:19: error: use of undeclared identifier 'nn_data'
   48 |         bias[i] = nn_data::bias[name][i];
      |                   ^
2 errors generated.
make[2]: *** [CMakeFiles/release.dir/build.make:90: CMakeFiles/release.dir/src/nnue/nnue.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:93: CMakeFiles/release.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

it seems `neural_network.hpp` is not `overwritten by generate_nn_header.cpp` : that `.hpp` file remains the same (having its 2 comment lines). That's why 'nn_data' is an undeclared identifier !?

[ i'm on Xubuntu 22.04 ]

**Comment by Nonlinear2** [comment]
Hello, and thanks for your feedback. Concerning the capital letter, I'll rename the file in the next commit. As for the error, it is indeed because the neural network header is not generated when building `release`, but only when building `generate_neural_net_header`. The reason I did this is that the neural network is not expected to change, so it would be slow to generate the header each time `release` is buit. If you can think of a better way to do it, please let me know! Anyway, I'll update the readme and add a clearer error message when the neural network header hasn't been generated.

**Comment by Nonlinear2** [comment]
Done!

**Comment by tissatussa** [comment]
indeed it seems you solved this Issue.
interpreting your last comment, i did this :

```
$ cmake . -DCMAKE_C_COMPILER=clang-17 -DCMAKE_CXX_COMPILER=clang++-17
-- The C compiler identification is Clang 17.0.6
-- The CXX compiler identification is Clang 17.0.6
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang-17 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++-17 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (0.8s)
-- Generating done (0.0s)
-- Build files have been written to: /home/roelof/Compiled/Bread-Engine-main-0.0.5-FIXED-compile

$ make generate_neural_net_header
[ 12%] Building CXX object CMakeFiles/generate_neural_net_header.dir/src/search_board.cpp.o
[ 25%] Building CXX object CMakeFiles/generate_neural_net_header.dir/src/nnue/nnue.cpp.o
[ 37%] Building CXX object CMakeFiles/generate_neural_net_header.dir/src/nnue/nnue_board.cpp.o
[ 50%] Building CXX object CMakeFiles/generate_neural_net_header.dir/src/transposition_table.cpp.o
[ 62%] Building CXX object CMakeFiles/generate_neural_net_header.dir/src/bread_engine_core.cpp.o
[ 75%] Building CXX object CMakeFiles/generate_neural_net_header.dir/dependencies/extern/Fathom/src/tbprobe.cpp.o
[ 87%] Building CXX object CMakeFiles/generate_neural_net_header.dir/utils/generate_nn_header.cpp.o
[100%] Linking CXX executable generate_neural_net_header
[100%] Built target generate_neural_net_header

$ ./generate_neural_net_header 

$ make release
[ 11%] Building CXX object CMakeFiles/release.dir/src/search_board.cpp.o
[ 22%] Building CXX object CMakeFiles/release.dir/src/nnue/nnue.cpp.o
[ 33%] Building CXX object CMakeFiles/release.dir/src/nnue/nnue_board.cpp.o
[ 44%] Building CXX object CMakeFiles/release.dir/src/transposition_table.cpp.o
[ 55%] Building CXX object CMakeFiles/release.dir/src/bread_engine_core.cpp.o
[ 66%] Building CXX object CMakeFiles/release.dir/dependencies/extern/Fathom/src/tbprobe.cpp.o
[ 77%] Building CXX object CMakeFiles/release.dir/src/uci.cpp.o
[ 88%] Building CXX object CMakeFiles/release.dir/src/run_uci.cpp.o
[100%] Linking CXX executable release
[100%] Built target release

$ ./release 
uci
id name Bread Engine 0.0.5
id author Nonlinear

option name SyzygyPath type string default <empty>
uciok
quit
```

> ..The reason I did this is that the neural network is not expected to change, so it would be slow to generate the header each time release is buit. If you can think of a better way to do it, please let me know!..

why should a user compile your source code into an UCI chess engine binary without a NNUE ? I think in the root a user should just do `cmake .` (and maybe supply the `clang` version as parameters, like i did) and then `make`. The `generate_neural_net_header` step can be included. The resulting binary can be named 'Bread-Engine-v0.0.5` or alike.

**Comment by tissatussa** [comment]
btw. v0.0.5 runs fine in CuteChess !

**Comment by Nonlinear2** [comment]
Hi, in the latest commit i've improved the build process, so now you only need to build release and the neural network header generation is handled implicitly.

**Comment by tissatussa** [comment]
indeed, now the make process works like that. Congrats !

in the README "For linux" you write `cmake . -DCMAKE_BUILD_TYPE=Release` but this command is executed in /build so `.` should be `..` : then compilation goes well.

you write `make release` but can we 'make' something else ? The help section of the makefile shows several targets, but i guess these are only for development ? I'm curious what else can be compiled .. if only 'release' is usable, can the argument `-DCMAKE_BUILD_TYPE=Release` be auto-included ? For me, executing `cmake .` followed by `make` is basic, you could auto-create the /build folder etc.

is AVX(2) involved ? I don't want to edit `CMakeLists.txt`, is argument `-mavx(2)` set ? And `-mbmi(2)` ? I guess this will profit certain CPUs.

**Comment by tissatussa** [comment]
once i stumbled upon a simple (?) general (!) NNUE chess engine called [BCE](https://github.com/TimosPal/NNUE-Bitboard-Chess-Engine) .. it's UCI and can work with any NNUE file (only the the "20 Mb type" however) but i had to compile those seperately, the net can not be set by an UCI option .. BCE is also written in C++, so you may have a look .. this engine can play rather strong (it depends on the NN) and moves very quickly! I could find the code part to set another max depth (because it's fixed) and compile such binary. I found several such 20 Mb NNUE files, eg. from the Arasan engine, all seem to differ in strength .. how is this simple (?) engine unique ? I found nothing like it so far ..

![brain-small](https://github.com/Nonlinear2/Bread-Engine/assets/1109281/bb3db1a4-4052-41de-85c8-b41bf5570527)

**Comment by Nonlinear2** [comment]
Thanks for pointing out the error in the cmake command, it is now fixed.

> you write make release but can we 'make' something else ? 

The other targets are meant for development:
- benchmark_engine runs some node/speed benchmarks on various positions
- parameter_tuning runs some experimental code to optimize piece square tables/move ordering coefficients using a perturbative approach.
- tests runs doctest tests.

However I can not garantee that these targets work when you clone a release, as they are not meant to be built by the user.

> AVX(2) involved ?

Yes, actually you need AVX2 to run the engine. In theory, it would be possible to write some code to make the engine run without AVX2, but it would make the engine weaker, and i don't think it is very useful as modern cpus support avx2.
In the CmakeLists, the argument `march=native` is set to enable AVX2.

As for your last question about BCE, it is off topic, but anyways it is not the only engine supporting external nnue files is it? I see the option `option name EvalFile type string` when running stockfish for instance.
